aws_region    = "us-east-1"
ami_id        = "ami-0360c520857e3138f"
instance_type = "t3.micro"
key_name      = "terraform"
db_name       = "wordpress"
db_username   = "wordpress"
db_password   = "changethis"
